version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 5.16.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
    - 3.9.9
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: webpack-command
    versions:
    - 0.5.0
